# Generated by Django 3.2.4 on 2021-11-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210625_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontact',
            name='obser',
            field=models.CharField(max_length=300),
        ),
    ]
