# Generated by Django 3.2.4 on 2021-11-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usercontact_obser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproduct',
            name='gender',
            field=models.IntegerField(choices=[[0, 'Masculino'], [1, 'Femenino']]),
        ),
    ]
