# Generated by Django 3.2.4 on 2021-11-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_newproduct_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproduct',
            name='brand',
            field=models.IntegerField(choices=[[0, 'SI'], [1, 'NO']]),
        ),
        migrations.AlterField(
            model_name='newproduct',
            name='gender',
            field=models.IntegerField(choices=[[0, 'Masculino'], [1, 'Femenino'], [2, 'No definido']]),
        ),
        migrations.AlterField(
            model_name='newproduct',
            name='size',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='newproduct',
            name='type',
            field=models.IntegerField(choices=[[0, 'Seguridad'], [1, 'Covid'], [2, 'Auto cuidado'], [3, 'Manejo de emociones'], [4, 'Psicologia de emergencia'], [5, 'Prevención y Manejo de Conflictos']]),
        ),
    ]
