# Generated by Django 3.2.4 on 2021-12-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_informe'),
    ]

    operations = [
        migrations.CreateModel(
            name='terrenocrud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal', models.CharField(max_length=50)),
                ('nomtec', models.CharField(max_length=50)),
                ('asunto', models.CharField(max_length=300)),
                ('nomempresa', models.CharField(max_length=300)),
                ('anteceden', models.CharField(max_length=300)),
                ('observacion', models.CharField(max_length=500)),
                ('observacion1', models.CharField(max_length=500)),
            ],
        ),
    ]
