# Generated by Django 3.2.4 on 2021-12-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_terrenocrud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrenocrud',
            name='anteceden',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='terrenocrud',
            name='asunto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='terrenocrud',
            name='nomempresa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='terrenocrud',
            name='observacion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='terrenocrud',
            name='observacion1',
            field=models.CharField(max_length=255),
        ),
    ]
